name: "Build on master and dev only"

on:
  push:
    branches:
      - master
      - dev

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 0
    - name: "setup python"
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: "install dependencies"
      run: |
        apt-get update -y && apt-get install -y git
        pip install -r requirements.txt
    - name: "check links"
      run: make linkcheck
    - name: "Build multiversioned doc"
      run: sphinx-multiversion source docs/html
    - name: "add .nojekill and redirect to master"
      run: |
        sudo touch docs/html/.nojekyll
        sudo tee docs/html/index.html << EOF
        <!DOCTYPE html>
        <html>
          <head>
            <title>Redirecting to master branch</title>
            <meta charset="utf-8">
            <meta http-equiv="refresh" content="0; url=./master/index.html">
            <link rel="canonical" href="https://spinalhdl.github.io/NaxRiscv-Rtd/master/index.html">
          </head>
        </html>
        EOF
    - name: Deploy to Pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: docs/html
