name: "Linkceck and buildtest on PR"

on:
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: "check links"
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "."
        build-command: "make linkcheck"
    - name: "test build"
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "."

